// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: chat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The top-level wrapper for all WebSocket messages
type WebSocketMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // For matching responses
	// Types that are valid to be assigned to Payload:
	//
	//	*WebSocketMessage_SignalMessage
	//	*WebSocketMessage_DeliveryReceipt
	//	*WebSocketMessage_TypingIndicator
	//	*WebSocketMessage_SyncRequest
	//	*WebSocketMessage_SyncResponse
	Payload       isWebSocketMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketMessage) Reset() {
	*x = WebSocketMessage{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketMessage) ProtoMessage() {}

func (x *WebSocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketMessage.ProtoReflect.Descriptor instead.
func (*WebSocketMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *WebSocketMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WebSocketMessage) GetPayload() isWebSocketMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebSocketMessage) GetSignalMessage() *SignalMessage {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_SignalMessage); ok {
			return x.SignalMessage
		}
	}
	return nil
}

func (x *WebSocketMessage) GetDeliveryReceipt() *DeliveryReceipt {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_DeliveryReceipt); ok {
			return x.DeliveryReceipt
		}
	}
	return nil
}

func (x *WebSocketMessage) GetTypingIndicator() *TypingIndicator {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_TypingIndicator); ok {
			return x.TypingIndicator
		}
	}
	return nil
}

func (x *WebSocketMessage) GetSyncRequest() *SyncRequest {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_SyncRequest); ok {
			return x.SyncRequest
		}
	}
	return nil
}

func (x *WebSocketMessage) GetSyncResponse() *SyncResponse {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_SyncResponse); ok {
			return x.SyncResponse
		}
	}
	return nil
}

type isWebSocketMessage_Payload interface {
	isWebSocketMessage_Payload()
}

type WebSocketMessage_SignalMessage struct {
	SignalMessage *SignalMessage `protobuf:"bytes,2,opt,name=signal_message,json=signalMessage,proto3,oneof"`
}

type WebSocketMessage_DeliveryReceipt struct {
	DeliveryReceipt *DeliveryReceipt `protobuf:"bytes,3,opt,name=delivery_receipt,json=deliveryReceipt,proto3,oneof"`
}

type WebSocketMessage_TypingIndicator struct {
	TypingIndicator *TypingIndicator `protobuf:"bytes,4,opt,name=typing_indicator,json=typingIndicator,proto3,oneof"`
}

type WebSocketMessage_SyncRequest struct {
	SyncRequest *SyncRequest `protobuf:"bytes,5,opt,name=sync_request,json=syncRequest,proto3,oneof"`
}

type WebSocketMessage_SyncResponse struct {
	SyncResponse *SyncResponse `protobuf:"bytes,6,opt,name=sync_response,json=syncResponse,proto3,oneof"`
}

func (*WebSocketMessage_SignalMessage) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_DeliveryReceipt) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_TypingIndicator) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_SyncRequest) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_SyncResponse) isWebSocketMessage_Payload() {}

// An encrypted message payload (Signal Protocol)
type SignalMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipientId   string                 `protobuf:"bytes,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"` // UUID
	Ciphertext    []byte                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`                      // Encrypted blob (includes header)
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`       // TimeUUID (assigned by client or server?) Usually client generates ID for idempotency
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalMessage) Reset() {
	*x = SignalMessage{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMessage) ProtoMessage() {}

func (x *SignalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMessage.ProtoReflect.Descriptor instead.
func (*SignalMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SignalMessage) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *SignalMessage) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *SignalMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SignalMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DeliveryReceipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryReceipt) Reset() {
	*x = DeliveryReceipt{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryReceipt) ProtoMessage() {}

func (x *DeliveryReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryReceipt.ProtoReflect.Descriptor instead.
func (*DeliveryReceipt) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *DeliveryReceipt) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeliveryReceipt) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *DeliveryReceipt) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TypingIndicator struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	IsTyping       bool                   `protobuf:"varint,2,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TypingIndicator) Reset() {
	*x = TypingIndicator{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingIndicator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingIndicator) ProtoMessage() {}

func (x *TypingIndicator) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingIndicator.ProtoReflect.Descriptor instead.
func (*TypingIndicator) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *TypingIndicator) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *TypingIndicator) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastMessageId string                 `protobuf:"bytes,1,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"` // Sync from this point
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *SyncRequest) GetLastMessageId() string {
	if x != nil {
		return x.LastMessageId
	}
	return ""
}

func (x *SyncRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*SignalMessage       `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *SyncResponse) GetMessages() []*SignalMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SyncResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\x04chat\"\xf5\x02\n" +
	"\x10WebSocketMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12<\n" +
	"\x0esignal_message\x18\x02 \x01(\v2\x13.chat.SignalMessageH\x00R\rsignalMessage\x12B\n" +
	"\x10delivery_receipt\x18\x03 \x01(\v2\x15.chat.DeliveryReceiptH\x00R\x0fdeliveryReceipt\x12B\n" +
	"\x10typing_indicator\x18\x04 \x01(\v2\x15.chat.TypingIndicatorH\x00R\x0ftypingIndicator\x126\n" +
	"\fsync_request\x18\x05 \x01(\v2\x11.chat.SyncRequestH\x00R\vsyncRequest\x129\n" +
	"\rsync_response\x18\x06 \x01(\v2\x12.chat.SyncResponseH\x00R\fsyncResponseB\t\n" +
	"\apayload\"\x8f\x01\n" +
	"\rSignalMessage\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\tR\vrecipientId\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertext\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"k\n" +
	"\x0fDeliveryReceipt\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"W\n" +
	"\x0fTypingIndicator\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tis_typing\x18\x02 \x01(\bR\bisTyping\"K\n" +
	"\vSyncRequest\x12&\n" +
	"\x0flast_message_id\x18\x01 \x01(\tR\rlastMessageId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"Z\n" +
	"\fSyncResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.chat.SignalMessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMoreB\"Z github.com/cipherchat/backend/pbb\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_chat_proto_goTypes = []any{
	(*WebSocketMessage)(nil), // 0: chat.WebSocketMessage
	(*SignalMessage)(nil),    // 1: chat.SignalMessage
	(*DeliveryReceipt)(nil),  // 2: chat.DeliveryReceipt
	(*TypingIndicator)(nil),  // 3: chat.TypingIndicator
	(*SyncRequest)(nil),      // 4: chat.SyncRequest
	(*SyncResponse)(nil),     // 5: chat.SyncResponse
}
var file_chat_proto_depIdxs = []int32{
	1, // 0: chat.WebSocketMessage.signal_message:type_name -> chat.SignalMessage
	2, // 1: chat.WebSocketMessage.delivery_receipt:type_name -> chat.DeliveryReceipt
	3, // 2: chat.WebSocketMessage.typing_indicator:type_name -> chat.TypingIndicator
	4, // 3: chat.WebSocketMessage.sync_request:type_name -> chat.SyncRequest
	5, // 4: chat.WebSocketMessage.sync_response:type_name -> chat.SyncResponse
	1, // 5: chat.SyncResponse.messages:type_name -> chat.SignalMessage
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	file_chat_proto_msgTypes[0].OneofWrappers = []any{
		(*WebSocketMessage_SignalMessage)(nil),
		(*WebSocketMessage_DeliveryReceipt)(nil),
		(*WebSocketMessage_TypingIndicator)(nil),
		(*WebSocketMessage_SyncRequest)(nil),
		(*WebSocketMessage_SyncResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
