// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: keys.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreKeyBundle struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IdentityKey           []byte                 `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	SignedPreKey          []byte                 `protobuf:"bytes,2,opt,name=signed_pre_key,json=signedPreKey,proto3" json:"signed_pre_key,omitempty"`
	SignedPreKeySignature []byte                 `protobuf:"bytes,3,opt,name=signed_pre_key_signature,json=signedPreKeySignature,proto3" json:"signed_pre_key_signature,omitempty"`
	OneTimePreKey         []byte                 `protobuf:"bytes,4,opt,name=one_time_pre_key,json=oneTimePreKey,proto3" json:"one_time_pre_key,omitempty"` // Optional
	OneTimePreKeyId       int32                  `protobuf:"varint,5,opt,name=one_time_pre_key_id,json=oneTimePreKeyId,proto3" json:"one_time_pre_key_id,omitempty"`
	SignedPreKeyId        int32                  `protobuf:"varint,6,opt,name=signed_pre_key_id,json=signedPreKeyId,proto3" json:"signed_pre_key_id,omitempty"`
	RegistrationId        int32                  `protobuf:"varint,7,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PreKeyBundle) Reset() {
	*x = PreKeyBundle{}
	mi := &file_keys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreKeyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreKeyBundle) ProtoMessage() {}

func (x *PreKeyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_keys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreKeyBundle.ProtoReflect.Descriptor instead.
func (*PreKeyBundle) Descriptor() ([]byte, []int) {
	return file_keys_proto_rawDescGZIP(), []int{0}
}

func (x *PreKeyBundle) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *PreKeyBundle) GetSignedPreKey() []byte {
	if x != nil {
		return x.SignedPreKey
	}
	return nil
}

func (x *PreKeyBundle) GetSignedPreKeySignature() []byte {
	if x != nil {
		return x.SignedPreKeySignature
	}
	return nil
}

func (x *PreKeyBundle) GetOneTimePreKey() []byte {
	if x != nil {
		return x.OneTimePreKey
	}
	return nil
}

func (x *PreKeyBundle) GetOneTimePreKeyId() int32 {
	if x != nil {
		return x.OneTimePreKeyId
	}
	return 0
}

func (x *PreKeyBundle) GetSignedPreKeyId() int32 {
	if x != nil {
		return x.SignedPreKeyId
	}
	return 0
}

func (x *PreKeyBundle) GetRegistrationId() int32 {
	if x != nil {
		return x.RegistrationId
	}
	return 0
}

type UploadKeysRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IdentityKey           []byte                 `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	SignedPreKey          []byte                 `protobuf:"bytes,2,opt,name=signed_pre_key,json=signedPreKey,proto3" json:"signed_pre_key,omitempty"`
	SignedPreKeySignature []byte                 `protobuf:"bytes,3,opt,name=signed_pre_key_signature,json=signedPreKeySignature,proto3" json:"signed_pre_key_signature,omitempty"`
	SignedPreKeyId        int32                  `protobuf:"varint,4,opt,name=signed_pre_key_id,json=signedPreKeyId,proto3" json:"signed_pre_key_id,omitempty"`
	OneTimePreKeys        []*OneTimePreKey       `protobuf:"bytes,5,rep,name=one_time_pre_keys,json=oneTimePreKeys,proto3" json:"one_time_pre_keys,omitempty"`
	RegistrationId        int32                  `protobuf:"varint,6,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UploadKeysRequest) Reset() {
	*x = UploadKeysRequest{}
	mi := &file_keys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadKeysRequest) ProtoMessage() {}

func (x *UploadKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadKeysRequest.ProtoReflect.Descriptor instead.
func (*UploadKeysRequest) Descriptor() ([]byte, []int) {
	return file_keys_proto_rawDescGZIP(), []int{1}
}

func (x *UploadKeysRequest) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *UploadKeysRequest) GetSignedPreKey() []byte {
	if x != nil {
		return x.SignedPreKey
	}
	return nil
}

func (x *UploadKeysRequest) GetSignedPreKeySignature() []byte {
	if x != nil {
		return x.SignedPreKeySignature
	}
	return nil
}

func (x *UploadKeysRequest) GetSignedPreKeyId() int32 {
	if x != nil {
		return x.SignedPreKeyId
	}
	return 0
}

func (x *UploadKeysRequest) GetOneTimePreKeys() []*OneTimePreKey {
	if x != nil {
		return x.OneTimePreKeys
	}
	return nil
}

func (x *UploadKeysRequest) GetRegistrationId() int32 {
	if x != nil {
		return x.RegistrationId
	}
	return 0
}

type OneTimePreKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         int32                  `protobuf:"varint,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneTimePreKey) Reset() {
	*x = OneTimePreKey{}
	mi := &file_keys_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneTimePreKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneTimePreKey) ProtoMessage() {}

func (x *OneTimePreKey) ProtoReflect() protoreflect.Message {
	mi := &file_keys_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneTimePreKey.ProtoReflect.Descriptor instead.
func (*OneTimePreKey) Descriptor() ([]byte, []int) {
	return file_keys_proto_rawDescGZIP(), []int{2}
}

func (x *OneTimePreKey) GetKeyId() int32 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *OneTimePreKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_keys_proto protoreflect.FileDescriptor

const file_keys_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"keys.proto\x12\x04keys\"\xbb\x02\n" +
	"\fPreKeyBundle\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\fR\videntityKey\x12$\n" +
	"\x0esigned_pre_key\x18\x02 \x01(\fR\fsignedPreKey\x127\n" +
	"\x18signed_pre_key_signature\x18\x03 \x01(\fR\x15signedPreKeySignature\x12'\n" +
	"\x10one_time_pre_key\x18\x04 \x01(\fR\roneTimePreKey\x12,\n" +
	"\x13one_time_pre_key_id\x18\x05 \x01(\x05R\x0foneTimePreKeyId\x12)\n" +
	"\x11signed_pre_key_id\x18\x06 \x01(\x05R\x0esignedPreKeyId\x12'\n" +
	"\x0fregistration_id\x18\a \x01(\x05R\x0eregistrationId\"\xa9\x02\n" +
	"\x11UploadKeysRequest\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\fR\videntityKey\x12$\n" +
	"\x0esigned_pre_key\x18\x02 \x01(\fR\fsignedPreKey\x127\n" +
	"\x18signed_pre_key_signature\x18\x03 \x01(\fR\x15signedPreKeySignature\x12)\n" +
	"\x11signed_pre_key_id\x18\x04 \x01(\x05R\x0esignedPreKeyId\x12>\n" +
	"\x11one_time_pre_keys\x18\x05 \x03(\v2\x13.keys.OneTimePreKeyR\x0eoneTimePreKeys\x12'\n" +
	"\x0fregistration_id\x18\x06 \x01(\x05R\x0eregistrationId\"8\n" +
	"\rOneTimePreKey\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\x05R\x05keyId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03keyB\"Z github.com/cipherchat/backend/pbb\x06proto3"

var (
	file_keys_proto_rawDescOnce sync.Once
	file_keys_proto_rawDescData []byte
)

func file_keys_proto_rawDescGZIP() []byte {
	file_keys_proto_rawDescOnce.Do(func() {
		file_keys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keys_proto_rawDesc), len(file_keys_proto_rawDesc)))
	})
	return file_keys_proto_rawDescData
}

var file_keys_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_keys_proto_goTypes = []any{
	(*PreKeyBundle)(nil),      // 0: keys.PreKeyBundle
	(*UploadKeysRequest)(nil), // 1: keys.UploadKeysRequest
	(*OneTimePreKey)(nil),     // 2: keys.OneTimePreKey
}
var file_keys_proto_depIdxs = []int32{
	2, // 0: keys.UploadKeysRequest.one_time_pre_keys:type_name -> keys.OneTimePreKey
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_keys_proto_init() }
func file_keys_proto_init() {
	if File_keys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keys_proto_rawDesc), len(file_keys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keys_proto_goTypes,
		DependencyIndexes: file_keys_proto_depIdxs,
		MessageInfos:      file_keys_proto_msgTypes,
	}.Build()
	File_keys_proto = out.File
	file_keys_proto_goTypes = nil
	file_keys_proto_depIdxs = nil
}
